# This is a basic workflow to help you get started with Actions
# 
# UPDATE:
#   - Secret keys
#   - GIT repos
#   - Folders

name: repo-sync

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 4 * * 5"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sync"
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
      DST_FOLD: play-area-sync/docs
      DST_NAME: play-area-sync
      DST_REPO: https://${{ secrets.DST_ACTOR }}:${{ secrets.DST_TOKEN }}@github.com/shsagir/play-area-sync.git
      DST_EMAIL: repo-sync@contoso.com
      DST_USER: repo-sync
      SRC_FOLD: play-area/docs
      SRC_NAME: play-area
      SRC_REPO: https://${{ secrets.SRC_ACTOR }}:${{ secrets.SRC_TOKEN }}@github.com/shsagir/play-area.git
    steps:
      - name: Clone SRC repo
        run: git clone --depth=1 $SRC_REPO
      - name: Clone DST repo
        run: git clone --depth=1 $DST_REPO
      - name: Copy doc changes
        run: cp -r $SRC_FOLD/* $DST_FOLD
      - name: Stage + Commit changes
        run: |
          TIMESTAMP=`date +"%Y-%m-%d_%H-%M-%S"`
          cd $DST_NAME
          git config user.email $DST_EMAIL
          git config user.name $DST_USER
          git commit -a -m "repo-sync $TIMESTAMP"
      - name: Push changes
        run:  |
          cd $DST_NAME
          git push $DST_REPO master
